// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwTzMKn_S93UhdTtRfuMhLCfRDnpZQExE',
    appId: '1:427341683657:web:afefddf9b900d82ed3e618',
    messagingSenderId: '427341683657',
    projectId: 'ind-classifieds-45f12',
    authDomain: 'ind-classifieds-45f12.firebaseapp.com',
    storageBucket: 'ind-classifieds-45f12.firebasestorage.app',
    measurementId: 'G-SB34V6SM29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQHqlkSmxN2atip2uR2XWZTvHg5QwLH7w',
    appId: '1:427341683657:android:5f0f082c22efedb6d3e618',
    messagingSenderId: '427341683657',
    projectId: 'ind-classifieds-45f12',
    storageBucket: 'ind-classifieds-45f12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWwkPzhNKIjI4HCy3rFT7FjMF2ZtgfvWo',
    appId: '1:427341683657:ios:23d6849f9e9c0c4bd3e618',
    messagingSenderId: '427341683657',
    projectId: 'ind-classifieds-45f12',
    storageBucket: 'ind-classifieds-45f12.firebasestorage.app',
    iosBundleId: 'com.ind.classifieds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWwkPzhNKIjI4HCy3rFT7FjMF2ZtgfvWo',
    appId: '1:427341683657:ios:23d6849f9e9c0c4bd3e618',
    messagingSenderId: '427341683657',
    projectId: 'ind-classifieds-45f12',
    storageBucket: 'ind-classifieds-45f12.firebasestorage.app',
    iosBundleId: 'com.ind.classifieds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwTzMKn_S93UhdTtRfuMhLCfRDnpZQExE',
    appId: '1:427341683657:web:8a4264793d6fa88dd3e618',
    messagingSenderId: '427341683657',
    projectId: 'ind-classifieds-45f12',
    authDomain: 'ind-classifieds-45f12.firebaseapp.com',
    storageBucket: 'ind-classifieds-45f12.firebasestorage.app',
    measurementId: 'G-0PLXLSKZQ4',
  );
}
